# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HIPLII
description: > # this means to ignore newlines until "baseurl:"
  Peluang usaha dropship / reseller fashion Jakarta Barat dan Tangerang.
  Grosir sepatu, sandal, tas, jaket, baju, celana murah.
url: "https://www.hiplii.com" # the base hostname & protocol for your site
logo: img/lipatan-square.png
logo-light: img/lipatan-rectangle.png
icon: img/favicon.ico
email: idhiplii@gmail.com
facebook: https://www.facebook.com/hiplii
fbmessenger: hiplii
twitter: https://twitter.com/hiplii
instagram: https://www.instagram.com/hiplii
pinterest: https://www.pinterest.com/hiplii/
author: HIPLII
twitusername: hiplii
disqus-shortname: hiplii
address-owner: Jl. Gaga Semanan RT 06 RW 04 No.53, Semanan, Kalideres, Jakarta Barat, 11850
telp: +62 852 1186 0081
nstelp: 6285211860081
line: http://line.me/ti/p/~hiplii
bca: 5271271035 a/n Heru Iryanto
bsm: 7119555706 a/n Heru Iryanto
google_site_verification: rAE_yObYTNwZzvqreXkPWROyvlkGY1feHdlKCc3thJA
google_analytics: UA-61959730-3
google_cse: 004200709654862820302:owlayxkjfs4

# Build settings
markdown: kramdown
permalink: /:title
paginate: 24
paginate_path: "/page:num"
gems:
  - jekyll-paginate